name: 知らせて.jp
baseurl: /
permalink: /news/:year/:month/:title
relative_permalinks: false
excerpt_separator: "<!-- more -->"

paginate: 5
paginate_path: "news/page/:num"

rss:
  baseurl: http://shirasete.jp

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: "http://shirasete.jp"
  relativeLinks: 'http://shirasete.jp/links.jsonp'
  media: "media"

  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "title"
        field:
          label: "Title"
          element: "text"

      - name: "date"
        field:
          label: "Date"
          element: "text"
          placeholder: "YYYY-MM-DD hh:mm:ss"

      - name: "author"
        field:
          label: "Author"
          element: "text"
          value: "Team 知らせて.jp"

      - name: "tags"
        field:
          label: "Tags"
          element: "multiselect"
          options: ["Announcement", "Mobile App", "Community"]
          alterable: true

      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true

